apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lovetest-nianshang-ingress
  namespace: lovetest-nianshang-ns
  labels:
    app: lovetest-nianshang
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/gzip-types: "text/plain,text/css,application/json,application/javascript,text/xml,application/xml,application/xml+rss,text/javascript"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - nianshang.lovetest.com.cn
    secretName: lovetest-nianshang-tls-secret
  rules:
  - host: nianshang.lovetest.com.cn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lovetest-nianshang-service
            port:
              number: 80
