apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lovetest-nianshang-ns

metadata:
  name: lovetest-nianshang
  namespace: lovetest-nianshang-ns

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- configmap.yaml
- env-configmap.yaml
- hpa.yaml

images:
- name: omaticaya/lovetest-nianshang
  newTag: 1.0.1

commonLabels:
  app: lovetest-nianshang
  managed-by: argocd


